# Google Ops agent configuration file
#
# ----- About -----
# path: /etc/google-cloud-ops-agent/config.yaml
# docs: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration
# repo: https://github.com/GoogleCloudPlatform/ops-agent
#
# ----- Usage -----
# sudo hx /etc/google-cloud-ops-agent/config.yaml
# sudo service google-cloud-ops-agent restart
# 
# ----- Trouble Shooting -----
# 
# sudo journalctl -xe | grep "google_cloud_ops_agent_engine"
#

---
logging:
  receivers:
    rent-picker-log:
      type: files
      include_paths:
        - /home/zumi/rent-picker/log/web-scraping/*/stackdriver_app.log*
  processors:
    parse_json:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%LZ"
    set_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
    set_source_location:
      type: modify_fields
      fields:
        sourceLocation.function:
          move_from: jsonPayload.target
  service:
    pipelines:
      custom_pipline:
        receivers:
          - rent-picker-log
        processors:
          - parse_json
          - set_severity
          - set_source_location
