version: '3.4'

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    env_file:
      - ./.open-telemetry/.env
    volumes:
      - type: bind
        source: ./.open-telemetry/otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
      - type: bind
        source: ./.open-telemetry/gcp-key-for-otel-collector.json
        target: /opt/open-telemetry/gcp-key-for-otel-collector.json
      - type: volume
        source: certs
        target: /usr/share/otel/config/certs
    ports:
      - "4317:4317"   # OTLP gRPC receiver

  sqlite-restore:
    image: litestream/litestream
    tty: true
    env_file:
      - ./.litestream/.env
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./.litestream
        target: /opt/litestream
    entrypoint: /bin/sh
    command: [-c, "
      rm -f /data/rent-picker.sqlite3 &&
      rm -f /data/rent-picker.sqlite3-shm &&
      rm -f /data/rent-picker.sqlite3-wal &&
      rm -rf /data/.rent-picker.sqlite3-litestream &&
      /usr/local/bin/litestream restore -config /opt/litestream/litestream.yaml /data/rent-picker.sqlite3
      "]

  web-scraping:
    image: us-west1-docker.pkg.dev/zumi-sandbox/rent-picker/web-scraping:release-bullseye-slim
    tty: true
    env_file:
      - web-scraping/dotenv/.env.docker
    depends_on:
      - 'sqlite-restore'
      - 'otel-collector'
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./log
        target: /log

  sqlite-backup:
    image: litestream/litestream
    tty: true
    env_file:
      - ./.litestream/.env
    depends_on:
      - 'web-scraping'
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./.litestream
        target: /opt/litestream
    entrypoint: /bin/sh
    command: [-c, "
      /usr/local/bin/litestream replicate -config /opt/litestream/litestream.yaml
      "]

volumes:
  certs:
    driver: local