[package]
name = "usecase"
version.workspace = true
edition.workspace = true
description.workspace = true


[dependencies]
domain.workspace = true
anyhow.workspace = true
async-trait.workspace = true
tracing.workspace = true
futures.workspace = true
url.workspace = true
indicatif.workspace = true