FROM lukemathwalker/cargo-chef:latest AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --bin cui

# We do not need the Rust toolchain to run the binary!
# debian:slim version
FROM debian:bullseye-slim AS runtime
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/target/debug/cui /usr/local/bin
# ENTRYPOINT ["/usr/local/bin/cui"]
ENTRYPOINT ["/bin/bash"]